---
- name: Playbook to test Vault
  hosts: all
  become: true
  vars_files:
    - vault-pass.yml
  tasks:
  - name: clone a git repo
    git:
      repo: https://Leticia-Mendes:{{ password }}@github.com/Leticia-Mendes/vault.git
      dest: /opt/ansadmin/test-vault
