---
- name: "install required packages"
  hosts: webservers
  become: true
  tasks:
  - name: install packages
    yum:
      name: "{{ item }}"
      state: installed
    with_items:
      - git
      - make
      - gcc
      - telnet
      - gzip

