---
- name: "tomcat setup"
  hosts: all
  become: true
  tasks:
    - name: "install java on RedHat"
      yum:
        name: java
        state: installed
      when: ansible_os_family == "RedHat"

    - name: "install java on ubuntu"
      apt:
        name: default-jdk
        state: present
      when: ansible_os_family == "Debian"

    - name: "download tomcat packages"
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.85/bin/apache-tomcat-8.5.85.zip
        dest: /opt

    - name: "untar apache packages"
      unarchive:
        src: /opt/apache-tomcat-8.5.85.zip
        dest: /opt
        remote_src: yes

    - name: "add execution permissions on catalina.sh file"
      file:
        path: /opt/apache-tomcat-8.5.85/bin/catalina.sh
        mode: 0777

    - name: "add execution permissions on startup.sh file"
      file:
        path: /opt/apache-tomcat-8.5.85/bin/startup.sh
        mode: 0777

    - name: "start tomcat services"
      shell: nohup bash ./startup.sh
      args:
        chdir: /opt/apache-tomcat-8.5.85/bin