---
# handlers file for setup-apache
- name: start httpd
  service:
    name: httpd
    state: started
  when: ansible_os_family == "RedHat"

- name: start apache
  service:
    name: apache2
    state: started
  when: ansible_os_family == "Debian"

- name: restart httpd
  service:
    name: httpd
    state: restarted
  when: ansible_os_family == "RedHat"

- name: restart apache
  service:
    name: apache2
    state: restarted
  when: ansible_os_family == "Debian"

